# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-28 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testDjango', '0004_usertable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTable',
        ),
    ]
