# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-28 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testDjango', '0005_delete_usertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=256, verbose_name='\u7528\u6237id')),
                ('userName', models.CharField(max_length=256, verbose_name='\u7528\u6237\u540d')),
                ('userNickName', models.CharField(max_length=256, verbose_name='\u7528\u6237\u6635\u79f0')),
                ('userSex', models.CharField(max_length=4, verbose_name='\u6027\u522b')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
        ),
    ]
