# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-15 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('userId', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='用户id')),
                ('userName', models.CharField(max_length=255, verbose_name='用户名')),
                ('userLevel', models.CharField(max_length=4, verbose_name='用户等级')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
        ),
    ]
