# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-15 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poison', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTable',
            new_name='bugUserTable',
        ),
    ]
